import NavButton from "@/app/navButton"
import Banner from "@/app/banner";
import Topic from "@/app/topic";
export default function Home() {
    return (  <div className="h-screen">
        <Banner name1="Professional" name2="Education" route1="./professional" route2="./education"></Banner>
        <div className="overflow-auto overscroll-none">
        <Topic image={'/img/texas.png'} title={'Texas Taco Week'} location={'Website'} start={'2024'} end={'Present'} description={'Built a website for the National Leadership Foundation to give information for their Texas Taco Week. built using Node.js and Tailwind.css.'} link={'./projects/pages/texas'}></Topic>
        <Topic image={'/img/f1.png'} title={'F1 Standings Extension'} location={'Chrome Extension'} start={'Jan 2022'} end={'Present'} description={'Developed a Chrome extension that scrapes the F1 website to gather information about driver standings, constructor standings, race results, and schedule information. It then displays this information in a lightweight UI that allows for easy use and stores the information locally to allow for use even without an internet connection. Currently supports an international user base of nearly 200 users. Built using HTML, CSS, and JavaScript.'} link={'./projects/pages/f1'}></Topic>
        <Topic image={'/img/vv.png'} title={'Virus Vision'} location={'Webapp'} start={'2024'} end={'2024'} description={'Virus Vision is a technology-driven project focused on disease surveillance and public health awareness, particularly targeting global health threats like Covid and Influenza. Utilizing statistics from the UK\'s public health organization, the project offers a detailed overview of disease spread and density relative to population, simplifying complex data for the public. It features a spatial bar-graph covering the United Kingdom, highlighting disease spread across England\'s nine regions. Challenges faced include API downtimes and difficulties in gathering relevant news articles. Despite setbacks, the team learned valuable skills in data parsing, frontend development, and API integration. Moving forward, the project aims to incorporate real-time data, expand disease coverage, support more countries, and include vaccination rates and nearby medical facilities, envisioning Virus Vision as a valuable tool for disease monitoring and public health education.'} link={'./projects/pages/virusVision'}></Topic>
        <Topic image={'/img/clash.png'} title={'Clash Wordale'} location={'Website'} start={'Dec 2023'} end={'Present'} description={'It is a web-based trivia game about the mobile game Clash Royale.'} link={'./projects/pages/clashWordale'}></Topic>
        <Topic image={'/img/perspective.png'} title={'A Different Perspective'} location={'Unity Game'} start={'2023'} end={'2023'} description={'A Different Perspective is a game designed to provide insight into the daily challenges faced by individuals dealing with different mental disorders and issues. With a focus on authenticity and empathy, the game comprises three levels, each immersing players in the experiences of individuals living with OCD, dyslexia, and body dysmorphia. Through gameplay, players navigate through scenarios that mirror real-life struggles, such as managing repetitive behaviors, overcoming reading difficulties, and coping with body image issues during social interactions. Developed using the Unity game engine and C# scripts, the project aims to foster greater awareness and understanding of mental health issues by offering players a firsthand perspective of these conditions.'} link={'./projects/pages/differentPerspective'}></Topic>
        <Topic image={'/img/bus.png'} title={'Better Urban Solutions'} location={'Webapp'} start={'2022'} end={'2022'} description={'Better Urban Solutions (B.U.S.) is a project aimed at addressing climate concerns by improving public transportation systems. Through data analysis, B.U.S. identifies gaps between public transport supply and demand in urban and suburban areas. By integrating data from sources like the Open Trip Map API and INRIX, the project evaluates bus stop utilization and population density around key locations such as San Francisco. This information helps optimize transit routes and identifies potential areas for new bus stops, with the goal of enhancing accessibility and promoting sustainable urban development. Developed with angular.js for the frontend and JavaScript/node.js for the backend, B.U.S. represents collaborative efforts to tackle important societal challenges.'} link={'./projects/pages/betterUrbanSolutions'}></Topic>
        <Topic image={'/img/cb.png'} title={'Crystal Ball'} location={'Webapp'} start={'2021'} end={'2021'} description={'Crystal Ball is a project designed to assist businesses in understanding consumer behavior by utilizing the INRIX API. Through this platform, businesses can access valuable insights into consumer trip patterns, aiding in marketing strategy optimization and decision-making processes. The platform offers an intuitive interface for visualizing trip data on maps and comparing data between different time frames. Developed with user-friendliness in mind, Crystal Ball aims to provide practical solutions for businesses seeking to enhance their understanding of consumer trends and optimize their operations accordingly.'} link={'./projects/pages/crystalBall'}></Topic>
        <Topic image={'/img/volun.png'} title={'Voluntarius'} location={'Flutter App'} start={'2022'} end={'2022'} description={'Voluntarius is an app born out of the need to connect volunteers with those seeking help in their community. Its core feature revolves around "Job Postings," where users can create tasks specifying details like time, description, and required volunteers. These postings are displayed on the home page of nearby volunteers, who can then assess and apply for tasks through an interactive map interface. Once a volunteer completes a task, their hours are verified by the host and can be exported in a PDF format, serving as motivation and a record of volunteer work. The app, developed using Flutter for the frontend and Firebase with node.js for the backend, emphasizes user experience and real-time communication, enhancing community engagement and collaboration. Looking ahead, Voluntarius aims to foster a supportive community by introducing additional features such as a local leaderboard and Single Sign-On integration with platforms like Google and Apple.'} link={'./projects/pages/voluntarius'}></Topic>
        <Topic image={'/img/homepage.png'} title={'Personal Website'} location={'Website'} start={'2024'} end={'Ongoing'} description={'Built this website from scratch using Next.js alongside Tailwind.css and hosted using Vercel.'} link={'./projects/pages/website'}></Topic>
       </div>
</div>
    );
}